name: process_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - seaborn=0.12.2
  - pandas=2.1.4
  - scikit-learn=1.3.0
  - matplotlib=3.8.0
  - pillow=10.0.1
  - mlflow=2.9.2
