main:
  experiment_name: demo-6
  mlflow_tracking_uri: http://localhost:5000
data:
  file_url: https://raw.githubusercontent.com/scikit-learn/scikit-learn/4dfdfb4e1bb3719628753a4ece995a1b2fa5312a/sklearn/datasets/data/iris.csv